name: Org Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-release:
    uses: Coalfire-CF/Actions/.github/workflows/org-release.yml@v0.0.20
