name: Org Checkov

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.hcl"
      - ".terraform.lock.hcl"
      - "**/terraform/**"

  workflow_call:
jobs:
  checkov-scan:
    uses: Coalfire-CF/Actions/.github/workflows/org-checkov.yml@v0.1.0
